name: "fastapi-app-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: stdin
  scan_frequency: 5s
  enabled: true
  fields:
    - service: app
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "app"

#filebeat.inputs:
#  - type: stdin
#    enabled: true
#    # Я запущу filebeat в докере и проброшу логи приложения по данному пути
##    paths:
##      - /host_metrics_app/host_metrics_app.log
#    # В fields мы можем указать дополнительные поля, а затем в logstash вытаскивать их
#    # и делать какую-нибудь дополнительную работу с логами
#    fields:
#      # Название нашего сервиса
#      service: app
#
#output.logstash:
#  # Будьте внимательны при запуске вне докера и вместо logstash укажите правильный адрес хоста с logstash.
#  hosts: ["logstash:5044"]
