registered_model:
  - bmp25
  - tfidf
  - 2stage_baseline
  - als

explained_model:
  als: "./service/weights/als/als_model-implicit.dill"

popular_items: ./service/data/knn/popular_mean_weight_item.csv
interactions: ./service/data/kion_train/interactions_with_avatar.csv
