pointwise:
  model_path: ./service/weights/pointwise/cbm_pointwise_all_data.dill
  data_user:
    path_users_features: ./service/data/kion_train/users_features.csv
    path_items_features: ./service/data/kion_train/items_features.csv
    columns:
      - lfm_score
      - rank
      - age
      - income
      - sex
      - kids_flg
      - user_hist
      - user_avg_pop
      - user_last_pop
      - release_year
      - genres
      - countries
      - for_kids
      - age_rating
      - studios
      - item_pop
      - item_avg_hist

