run_params:
  type_reco: offline  # can have two meanings: offline / online
  artifact:
    offline_reco_path: ./service/data/knn/bmp_25_k60_rectools.csv  # if type_reco = 'online' then field not use
    model_path_1: ./service/weights/knn/tfidf-k60-implicit.dill  # if type_reco = 'offline' then field not use
    model_path_2: ./service/weights/knn/bmp25-k60-implicit.dill  # if blending = False then field not use
    index_bmp_model: -1  # index bmp model (if -1 then bmp model not use)
    blending: False  # if type_reco = 'offline' then field not use
