user_embeddings: ./service/weights/lfm/lfm_users.npy
item_embeddings: ./service/weights/lfm/lfm_items.npy
approximate_search:
  space_name: 'negdotprod'
  method: 'hnsw'
  index_time_params:
    M: 64
    efConstruction: 1000
    indexThreadQty: 4
  query_time_params:
    efSearch: 1000
